# #Creating Arrays

In [2]:
import numpy as np
arr=np.array([12,21,32,46,54,69,78])
print(arr)
print(type(arr))

[12 21 32 46 54 69 78]
<class 'numpy.ndarray'>


In [3]:
import numpy as np
t=(2,4,6,8)
a=np.array(t)
print(type(t))
print(type(a))
print(a)

<class 'tuple'>
<class 'numpy.ndarray'>
[2 4 6 8]


# NdArray

In [4]:
import numpy as np
b=np.array(12)
print(b)
print(b.ndim)

12
0


In [5]:
import numpy as np
c=np.array([1,2,3,4])
print(c)
print(c.ndim)

[1 2 3 4]
1


In [6]:
import numpy as np
d=np.array([[1,2],[3,4]])
print(d)
print(d.ndim)

[[1 2]
 [3 4]]
2


In [7]:
import numpy as np
e=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(e)
print(e.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


In [8]:
f=np.array([[[[[[2]]]]]])
print(f)
print(f.ndim)

[[[[[[2]]]]]]
6


# Access Array Elements

In [9]:
print(a)

[2 4 6 8]


In [10]:
print(a[1])

4


In [11]:
print(e)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
print(e[0,1,1])

4


In [13]:
print(d)

[[1 2]
 [3 4]]


In [14]:
print(d[1,1])

4


In [15]:
print(d[1,-1])

4


In [16]:
print(e[0,1,-1])

4


In [17]:
print(e[0,-1])

[3 4]


# Array Slicing

In [18]:
print(arr)

[12 21 32 46 54 69 78]


In [19]:
print(arr[1:6])

[21 32 46 54 69]


In [20]:
print(arr[4:])

[54 69 78]


In [21]:
print(arr[:5])

[12 21 32 46 54]


In [22]:
print(arr[-7:-3])

[12 21 32 46]


In [23]:
print(arr[0:7:3])

[12 46 78]


# Data Types

In [24]:
import numpy as np
z=np.array([1,2,3])
y=np.array(['a','b','c','d'])
print(z)
print(z.dtype)
print(y)
print(y.dtype)

[1 2 3]
int32
['a' 'b' 'c' 'd']
<U1


In [25]:
x=np.array([1,2,3],dtype='S')
print(x)
print(x.dtype)

[b'1' b'2' b'3']
|S1


In [26]:
w=np.array([1,2,3,4],dtype='i4')
print(w)
print(w.dtype)

[1 2 3 4]
int32


In [27]:
import numpy as np
v=np.array([1,2.3,3.4,5,0])
newv=v.astype('i')
newv1=v.astype('f')
newv2=v.astype('bool')
print(newv)
print(newv.dtype)
print(newv1)
print(newv1.dtype)
print(newv2)
print(newv2.dtype)

[1 2 3 5 0]
int32
[1.  2.3 3.4 5.  0. ]
float32
[ True  True  True  True False]
bool


# Difference between Copy & View

In [28]:
print(arr)

[12 21 32 46 54 69 78]


In [29]:
u=arr.copy()
arr[0]=5
print(arr)
print(u)

[ 5 21 32 46 54 69 78]
[12 21 32 46 54 69 78]


In [30]:
t=arr.view()
arr[0]=10
print(arr)
print(t)

[10 21 32 46 54 69 78]
[10 21 32 46 54 69 78]


In [33]:
print(arr)

[10 21 32 46 54 69 78]


In [34]:
g=arr.copy()
h=arr.view()
print(g.base)
print(h.base)

None
[10 21 32 46 54 69 78]
